version: "2"

services:
  zk:
    image: zookeeper
    network_mode: host
    environment:
      ZK_CONFIG: tickTime=2000,initLimit=10,syncLimit=5,maxClientCnxns=128,forceSync=no,clientPort=2181
      ZK_ID: 1
    restart: always

  master:
    image: mesosphere/mesos-master:1.2.0-rc2
    network_mode: host
    ports:
      - "5050:5050"
    expose:
      - "5050"
    environment:
      MESOS_ZK: zk://127.0.0.1:2181/mesos
      MESOS_QUORUM: 1
      MESOS_CLUSTER: docker-compose
      MESOS_REGISTRY: replicated_log # default is in_memory for some reason
      MESOS_HOSTNAME: ${DOCKER_IP}
      LIBPROCESS_IP: ${DOCKER_IP}
    depends_on:
      - zk
    restart: always

  slave-one:
    image: mesosphere/mesos-slave:1.2.0-rc2
    network_mode: host
    pid: host
    environment:
      MESOS_MASTER: zk://127.0.0.1:2181/mesos
      MESOS_CONTAINERIZERS: docker,mesos
      MESOS_PORT: 5051
      MESOS_RESOURCES: ports(*):[11000-11999]
      MESOS_ATTRIBUTES: lab_role:worker
      MESOS_HOSTNAME: slave1.${DOCKER_IP}.xip.io
      LIBPROCESS_IP: ${DOCKER_IP}
      MESOS_WORK_DIR: /tmp/mesos
    volumes:
      - /sys/fs/cgroup:/sys/fs/cgroup
      - /usr/local/bin/docker:/usr/bin/docker
      - /var/run/docker.sock:/var/run/docker.sock
    depends_on:
      - zk
    restart: always

  slave-two:
    image: mesosphere/mesos-slave:1.2.0-rc2
    network_mode: host
    pid: host
    environment:
      MESOS_MASTER: zk://127.0.0.1:2181/mesos
      MESOS_CONTAINERIZERS: docker,mesos
      MESOS_PORT: 5052
      MESOS_RESOURCES: ports(*):[12000-12999]
      MESOS_ATTRIBUTES: lab_role:worker
      MESOS_HOSTNAME: slave2.${DOCKER_IP}.xip.io
      LIBPROCESS_IP: ${DOCKER_IP}
      MESOS_WORK_DIR: /tmp/mesos
    volumes:
      - /sys/fs/cgroup:/sys/fs/cgroup
      - /usr/local/bin/docker:/usr/bin/docker
      - /var/run/docker.sock:/var/run/docker.sock
    depends_on:
      - zk
    restart: always

  slave-three:
    image: mesosphere/mesos-slave:1.2.0-rc2
    network_mode: host
    pid: host
    environment:
      MESOS_MASTER: zk://127.0.0.1:2181/mesos
      MESOS_CONTAINERIZERS: docker,mesos
      MESOS_PORT: 5053
      MESOS_RESOURCES: ports(*):[8000-10999]
      MESOS_ATTRIBUTES: lab_role:control
      MESOS_HOSTNAME: slave3.${DOCKER_IP}.xip.io
      LIBPROCESS_IP: ${DOCKER_IP}
      MESOS_WORK_DIR: /tmp/mesos
    volumes:
      - /sys/fs/cgroup:/sys/fs/cgroup
      - /usr/local/bin/docker:/usr/bin/docker
      - /var/run/docker.sock:/var/run/docker.sock
    depends_on:
      - zk
    restart: always

  marathon:
    image: mesosphere/marathon:v1.4.1
    network_mode: host
    ports:
      - "8080:8080"
    expose:
      - "8080"
    environment:
      MARATHON_MASTER: zk://127.0.0.1:2181/mesos
    depends_on:
      - zk
    restart: always

  etcd:
    image: elcolio/etcd:latest
    expose:
      - "4001"
      - "2379"
    ports:
      - "4001:4001"
      - "2379:2379"
    restart: always

  db:
    image: percona:5.6
    volumes:
    - ./fixtures:/docker-entrypoint-initdb.d
    expose:
      - "3306"
    ports:
      - "3306:3306"
    environment:
      MYSQL_ROOT_PASSWORD: password
    restart: always

  # source: https://coderwall.com/p/dtwc1q/insecure-and-self-signed-private-docker-registry-with-boot2docker
  registry:
    # build: ./registry
    image: registry:2.5.1
    restart: always
    ports:
    - '5000:5000'
    expose:
      - 5000
    environment:
      TCP_PORTS: '5000'
      VIRTUAL_HOST: '*:5000, https://*:5000'
      FORCE_SSL: 'true'
      REGISTRY_STORAGE_DELETE_ENABLED: 'true'
      REGISTRY_HTTP_TLS_CERTIFICATE: '/certs/domain.crt'
      REGISTRY_HTTP_TLS_KEY: '/certs/domain.key'
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      - ./certs:/certs
      - ./data:/var/lib/registry


  pyspark:
    image: jupyter/pyspark-notebook
    network_mode: host
    pid: host
    # --pid=host -e TINI_SUBREAPER=true
    # --net=host
    restart: always
    ports:
    - '8888:8888'
    expose:
      - 8888
    environment:
      TCP_PORTS: '8888'
      TINI_SUBREAPER: 'true'
    stdin_open: true
    tty: true
