# NOTE: Run this w/ docker-compose -f
  pyspark:
    image: jupyter/pyspark-notebook
    network_mode: host
    pid: host
    # --pid=host -e TINI_SUBREAPER=true
    # --net=host
    restart: always
    ports:
    - '8888:8888'
    expose:
      - 8888
    environment:
      TCP_PORTS: '8888'
      TINI_SUBREAPER: 'true'
    stdin_open: true
    tty: true
